import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';


// For flatpickr
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

//TODO: straigfht from AI look into how  it does it. 
const ignoreCssImports = {
	name: "ignore-css-imports",
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, () => ({ contents: "", loader: "js" }));
	}
};

const appendFlatpickrCss = {
	name: "append-flatpickr-css",
	setup(build) {
		build.onEnd(() => {
			const flatpickrCss = path.resolve("node_modules/flatpickr/dist/flatpickr.min.css");
			const stylesDest = path.resolve("styles.css");
			if (fs.existsSync(flatpickrCss)) {
				const fpCss = fs.readFileSync(flatpickrCss, "utf8");
				const existing = fs.existsSync(stylesDest) ? fs.readFileSync(stylesDest, "utf8") : "";
				const marker = "/* flatpickr */";
				const base = existing.includes(marker)
					? existing.slice(0, existing.indexOf(marker))
					: existing;
				fs.writeFileSync(stylesDest, `${base}\n${marker}\n${fpCss}`);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	//TODO: look into why this is needed
	plugins: [ignoreCssImports, appendFlatpickrCss],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
